/**
 * Postinstall script to create Node.js-compatible alias for @auth/create
 * 
 * This resolves the module resolution issue where:
 * - Vite uses aliases defined in vite.config.ts during build
 * - Node.js runtime needs the package to exist in node_modules
 * 
 * The @auth/create alias points to ./src/__create/@auth/create.js
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const projectRoot = path.resolve(__dirname, '..');

const targetDir = path.join(projectRoot, 'node_modules', '@auth', 'create');
const packageJsonPath = path.join(targetDir, 'package.json');
const indexJsPath = path.join(targetDir, 'index.js');

// Create directory structure
fs.mkdirSync(targetDir, { recursive: true });

// Create package.json
const packageJson = {
  name: '@auth/create',
  version: '1.0.0',
  type: 'module',
  main: 'index.js',
  private: true,
  description: 'Local alias for @auth/create - auto-generated by postinstall'
};
fs.writeFileSync(packageJsonPath, JSON.stringify(packageJson, null, 2));

// Create index.js that re-exports from the actual location
const indexContent = `// Auto-generated by scripts/postinstall.js
// Re-exports from the actual @auth/create implementation
export { default } from '../../../src/__create/@auth/create.js';
export * from '../../../src/__create/@auth/create.js';
`;
fs.writeFileSync(indexJsPath, indexContent);

console.log('[postinstall] Created @auth/create alias in node_modules');

